/**
 * zenNodes v0.3.0
 * A Javascript implementation of Zen Coding that generates DOM nodes. 
 * 
 * Copyright (c) 2011 Phuong Phan
 * Release under the MIT license.
 * 
 * Design credits goes to Zen Coding author(s).
 * http://code.google.com/p/zen-coding/
 */
var g=null;
(function(i,h){function b(a,d){var c=b.t(a);c.input.length&&b.error("Syntax error: expecting "+b.d[c.g].join(", ")+" token after "+(c.c.length?b.a.h(c.c).name:"$start"));b.a.B(b.d[c.g])||b.error("Syntax error: unterminated "+c.g+" expecting "+b.d[c.g].join(", ")+" token");delete c.input;delete c.g;c.c.push(new b.m.o("$end",h,"$end"));return b.parse(c,d)}b.t=function(a){var a={input:a,g:"$start",c:[]},d="",c="";do if(d=b.z(a.input,a.g))c=b.A(a.input,d),a.c.push(new b.m.o(d,b.c[d].type,c[b.c[d].value])),a.input=
a.input.substr(c[0].length),a.g=d;while(a.input.length&&d);return a};b.error=function(a){throw"zenNodes: "+a;};b.parse=function(a,d){a.b=g;a.data={};a.i=g;a.parent=[];a.root=d||b.a.w();a.parent.push(a.root);var c=g,e=0,f=a.c.length;for(b.rules.s(a.data);e<f;e++){c=a.c[e];if(c.name in b.f)b.f[c.name](a,c,e);b.rules.r(a.data,c);if(c.name in b.rules)b.rules[c.name](a.data,c)}return a.root};b.z=function(a,d){for(var c=b.d,e=0,f=c[d].length;e<f;e++)if(c[d][e]!="$end"&&b.c[c[d][e]].pattern.test(a))return c[d][e]};
b.A=function(a,d){if("block"in b.c[d]){var c=a.substr(0,b.a.v(a,b.c[d].u));return[c,c]}return b.c[d].pattern.exec(a)};b.a={};b.k={};b.m={};b.j={n:1,D:2,l:3};b.c={attribute:{value:1,pattern:/^(\[)/},attributeEnd:{value:1,pattern:/^(])/},attributeName:{value:1,pattern:/^([a-zA-Z_:][\w:.-]+)/},attributeSeparator:{value:1,pattern:/^( )/},attributeValue:{value:2,pattern:/^=('|")?([^\1]+?)\1/},autocomplete:{value:1,pattern:/^(\+)$/},"class":{value:1,pattern:/^\.([\w-_]+)/},descendant:{value:1,pattern:/^(>)/},
group:{value:1,pattern:/^(\()/},groupContents:{value:1,pattern:/^([^)]+)/,type:b.j.l,u:{start:"(",end:")"}},groupEnd:{value:1,pattern:/^(\))/},id:{value:1,pattern:/^#([\w-_]+)/},multiplier:{value:1,pattern:/^\*([\d]+)/,type:b.j.n},placeholder:{value:1,pattern:/^(\$+)/},sibling:{value:1,pattern:/^(\+)/},tag:{value:1,pattern:/^([a-z]+)/},text:{value:1,pattern:/^({)/},textContents:{value:1,pattern:/^(.*?(?:[^\\])(?![^}]+))/,type:b.j.l},textEnd:{value:1,pattern:/^(})/}};b.d={$start:["attribute","class",
"id","tag","text"],$afterTag:"attribute,class,descendant,id,multiplier,sibling,text".split(","),attribute:["attributeName"],attributeEnd:["$end","$afterTag"],attributeName:["attributeEnd","attributeValue"],attributeSeparator:["attributeName"],attributeValue:["attributeEnd","attributeSeparator"],autocomplete:["$end"],"class":["$end","$afterTag","placeholder"],descendant:["$afterTag","group","tag"],group:["groupContents"],groupContents:["groupEnd"],groupEnd:["$end","multiplier","sibling"],id:["$end",
"$afterTag","placeholder"],multiplier:["$end","descendant","sibling"],placeholder:["$end","descendant","multiplier"],sibling:["$afterTag","group","tag"],tag:["$end","$afterTag","autocomplete"],text:["textContents"],textContents:["textEnd"],textEnd:["$end","$afterTag"]};b.rules={s:function(a){if(!("attributes"in a))a.attributes={};if(!("counters"in a))a.e={}},r:function(a,b){a.e[b.name]=!(b.name in a.e)?1:a.e[b.name]+1},attribute:function(a){a.e.F>1&&b.error("Too many attributes defined: only one [] is needed")},
attributeEnd:function(a){a.attributes={}},attributeName:function(a,d){d.value in a.attributes?b.error("Attribute name already defined: "+d.value):a.attributes[d.value]=true},descendant:function(a){a.e={}},id:function(a){a.e.id>1&&b.error("Too many IDs defined: a tag can only have one ID")},sibling:function(a){a.e={}},text:function(a){a.e.text>1&&b.error("Too many text defined: a tag can only have one text node")}};b.f={$end:function(a,d,c){if(a.i){for(var d=a.i.nodeType==11?b.a.getParent(a.parent):
a.i.parentNode,e=1,c=b.a.h(a.c,c,function(a){return a.name=="multiplier"}).value;e<c;e++)d.appendChild(a.i.cloneNode(true));b.f.multiplier.q(d.childNodes)}},attribute:function(a){if(!a.b)a.b=b.a.getParent(a.parent).appendChild(document.createElement("div"))},attributeName:function(a,b){a.b.hasAttribute(b.value)||a.b.setAttribute(b.value,"")},attributeValue:function(a,d,c){a.b.setAttribute(b.a.h(a.c,c).value,d.value)},"class":function(a,d){if(!a.b)a.b=b.a.getParent(a.parent).appendChild(document.createElement("div"));
a.b.className+=(a.b.className?" ":"")+d.value},descendant:function(a){a.parent.push(a.b);a.b=g},groupContents:function(a,d){b.a.getParent(a.parent).appendChild(b(d.value))},id:function(a,d){if(!a.b)a.b=b.a.getParent(a.parent).appendChild(document.createElement("div"));a.b.id=d.value},multiplier:function(a,d,c){a.i=b.a.h(a.c,c).name=="groupEnd"?b(b.a.h(a.c,c,function(a){return a.name=="groupContents"}).value):a.b},placeholder:function(a,d,c){for(var c=b.a.h(a.c,c,function(a){return a.name=="id"||a.name==
"class"}),a=b.a.getParent(a.parent),e=0,f=a.childNodes.length;e<f;e++)switch(c.name){case "class":a.childNodes[e].className+=d.value;break;case "id":a.childNodes[e].id+=d.value}},sibling:function(a){a.b=g},tag:function(a,d){a.b=b.a.getParent(a.parent).appendChild(document.createElement(d.value))},textContents:function(a,d){var c=a.b||b.a.getParent(a.parent);"innerHTML"in c&&(c.innerHTML+=d.value)}};b.f.multiplier.replace=function(a,d){for(var c=["id","className"],e=0,f=c.length;e<f;e++)a[c[e]].indexOf("$")>
-1&&(a[c[e]]=a[c[e]].replace(/(\$+)/,function(a){return b.a.padding(d,a.length,"0")}))};b.f.multiplier.q=function(a,d){for(var c=0,e=a.length;c<e;c++)b.f.multiplier.replace(a[c],(d!==h?d:c)+1),b.f.multiplier.q(a[c].childNodes,d!==h?d:c)};b.a.v=function(a,d){var c=1,e=a.charAt(0)==d.start?1:0,f=a.length;for(b.a.p(a,d.start)>b.a.p(a,d.end)&&b.error("unterminated block: expecing "+d.end);e<f;e++)if(a.charAt(e)==d.start?c++:a.charAt(e)==d.end&&c--,!c)return e;b.error("unterminated block: expecting "+
d.end)};b.a.p=function(a,b){return a.split(b).length-1};b.a.w=function(){return document.createDocumentFragment()};b.a.h=function(a,b,c){if(c!==h)for(var e=b;e>=0;e--)if(c(a[e],e,a))return a[e];return a[(b||a.length)-1]};b.a.getParent=function(a,b){return a[a.length-(b||1)]};b.a.B=function(a){for(var b=0,c=a.length;b<c;b++)if(a[b]=="$end")return true;return false};b.a.padding=function(a,b,c){a=""+a;return a.length<b?Array(b-a.length+1).join(c)+a:a};b.k=function(){b.k.C()};b.k.C=function(){var a={},
d="",c=g,e=0;for(d in b.d)d.charAt(0)=="$"&&d!="$start"&&(a[d]=b.d[d],delete b.d[d]);for(d in b.d){c=b.d[d];for(e=0;e<c.length;)c[e].charAt(0)=="$"&&c[e]!="$start"&&(c[e]in a?(Array.prototype.push.apply(c,a[c[e]]),c.splice(e,1)):c[e]!="$end"&&b.error("Transition set not defined: "+c[e])),e++}};b.m.o=function(a,d,c){this.name=a;this.type=d;this.value=c;switch(this.type){case b.j.n:this.value=parseFloat(c);break;case b.j.l:this.value=c.replace(/\\(.)/g,"$1")}};b.k();i.zenNodes=function(a,d){return b(a,
d)}})(this);